import { Anilist } from "../src";

const query = Anilist.query.media()
    .withId()
    .withMalId()
    .withTitles()
    .withType()
    .withFormat()
    .withStatus()
    .withDescription()
    .withStartDate()
    .withEndDate()
    .withSeason()
    .withSeasonYear()
    .withSeasonInt()
    .withEpisodes()
    .withDuration()
    .withChapters()
    .withVolumes()
    .withCountryOfOrigin()
    .isLicensed()
    .withSource()
    .withTwitterHashtag()
    .withTrailer()
    .updatedAt()
    .withCoverImage()
    .withBannerImage()
    .withGenres()
    .withSynonyms()
    .withAverageScore()
    .withMeanScore()
    .withPopularity()
    .isLocked()
    .withTrending()
    .withFavourites()
    .withTags()
    .withRelations()
    .withCharacters()
    .withStaff()
    .withStudios()
    .isFavourite()
    .isFavouriteBlocked()
    .isAdult()
    .withNextAiringEpisode()
    .withAiringSchedule()
    .withTrends()
    .withExternalLinks()
    .withStreamingEpisodes()
    .withRankings()
    .withMediaListEntries()
    .withReviews()
    .withRecommendations()
    .withStats();
(async () => {
    console.log(await query.fetch())
})()