import { anilist } from "../src";

const query = anilist.query.media()
    .withId()
    .withMalId()
    .withTitles()
    .withType()
    .withFormat()
    .withStatus()
    .withDescription()
    .withStartDate()
    .withEndDate()
    .withSeason()
    .withSeasonYear()
    .withSeasonInt()
    .withEpisodes()
    .withDuration()
    .withChapters()
    .withVolumes()
    .withCountryOfOrigin()
    .isLicensed()
    .withSource()
    .withTwitterHashtag()
    .withTrailer()
    .updatedAt()
    .withCoverImage()
    .withBannerImage()
    .withGenres()
    .withSynonyms()
    .withAverageScore()
    .withMeanScore()
    .withPopularity()
    .isLocked()
    .withTrending()
    .withFavourites()
    .withTags()
    .withRelations()
    .isFavourite()
    .isFavouriteBlocked()
    .isAdult()
    .withNextAiringEpisode()
    .withExternalLinks()
    .withStreamingEpisodes()
    .withRankings()
    .withMediaListEntries();
(async () => {
    console.log(await query.fetch())
})()